
    server:
      port: 8080

    spring:
      datasource:
        url: jdbc:postgresql://120.79.71.187:5432/harfid2
        username: postgres
        password: pg@1102E
        driver-class-name: org.postgresql.Driver

    # 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
    mybatis:
      mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
      type-aliases-package: com.yufeng.yfps.model  # 注意：对应实体类的路径

#    #pagehelper分页插件
#    pagehelper:
#      helperDialect: mysql
#      reasonable: true
#      supportMethodsArguments: true
#      params: count=countSql